server:
    port: 10086
spring:
    application:
        name: leyou-registry
eureka:
    client:
        service-url:
            defaultZoom: http://localhost:${server.port}/eureka
        register-with-eureka: false # 把自己注册到eureka服务列表
        fetch-registry: false # 拉取eureka服务信息
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

#eureka:
#    server:
#        enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
#        eviction-interval-timer-in-ms: 1000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
#eureka:
#    client:
#        service-url:
#            defaultZoom: http://localhost:10086/eureka
#    server:
#            enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
#            eviction-interval-timer-in-ms: 10000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
